import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "m-0 bg-black px-5 ")}>
        <main className=" top-0 m-0 flex h-full min-h-screen flex-col justify-between p-0 ">
          {" "}
          <Navbar />
          <div className=" flex w-full items-center justify-center self-center ">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
