import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={clsx(inter.className, '')}>
				<main className='bg-black top-0 h-screen flex-col flex'>
					{' '}
					<Navbar />
					{children}
					<Footer />
				</main>
			</body>
		</html>
	);
}
